### ISSUE TITLE
Can't install qdldl via setup.py

### ISSUE THREAD

**Issue by sbarratt** [oxfordcontrol/qdldl-python#10] opened 2020-05-19 18:51 UTC
In a blank folder, here's my setup.py:

```
from setuptools import setup, find_packages

setup(
    name="test",
    packages=find_packages(),
    install_requires=[
        "qdldl",
    ],
)
```

When I run `python setup.py install`, I get the following printout:
```
CMake Error: The source directory "/tmp/easy_install-w2_fim2u/qdldl-0.1.1/c" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
cpp/qdldl.cpp:1:10: fatal error: qdldl.hpp: No such file or directory
 #include "qdldl.hpp"
          ^~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by sbarratt** [comment] 2020-05-19 18:57
This isn't working through pip either. Here are the exact commands I ran.

```
python3 -m venv env
source env/bin/activate
pip install qdldl
```

Here's the error:
```
    Complete output from command /home/shane/Downloads/tmp/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xn1h2m9e/qdldl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-apewkus1-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/shane/Downloads/tmp/env/include/site/python3.6/qdldl:
    running install
    running build
    running build_ext
    CMake Error: The source directory "/tmp/pip-build-xn1h2m9e/qdldl/c" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    Error: could not load cache
    building 'qdldl' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpp
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ic -Ic/qdldl/include -I/home/shane/Downloads/tmp/env/lib/python3.6/site-packages/pybind11/include -I/home/shane/Downloads/tmp/env/lib/python3.6/site-packages/pybind11/include -I/home/shane/Downloads/tmp/env/include -I/usr/include/python3.6m -c cpp/qdldl.cpp -o build/temp.linux-x86_64-3.6/cpp/qdldl.o -O3 -std=c++11
    cpp/qdldl.cpp:1:10: fatal error: qdldl.hpp: No such file or directory
     #include "qdldl.hpp"
              ^~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
```

**Comment by bstellato** [comment] 2020-05-20 03:28
Thanks for reporting this issue. It is the same weird error that I am getting when I try to create the [qdldl-feedstock](https://github.com/conda-forge/staged-recipes/pull/11277) for conda. Apparently the header file `qdldl.hpp` does not appear in that folder.

The weird thing is that the github actions CI works perfectly and builds the python wheels for any platform. At the moment I cannot reproduce it locally but I will try.

Regarding the `pip` install option, I created the manylinux2010 wheels on pypi. You should be able to install them without having to compile anything. Do you have a recent version of pip that is compatible with manylinux2010?

**Comment by sbarratt** [comment] 2020-05-21 19:52
Oh, wow! Yeah. Running `pip install --upgrade pip` solved it.

**Comment by bstellato** [comment] 2020-05-25 14:36
@sbarratt I just thought that it might be an issue with setuptools. Do you mind sharing your version? `python -m easy_install --version`

**Comment by sbarratt** [comment] 2020-05-26 19:33
Yeah, for a new venv on my machine, it's "setuptools 39.0.1"

Best,
Shane

**Comment by bstellato** [comment] 2020-05-26 23:29
I have `41.2.0`. Could you please try `pip install -U setuptools` and then `python setup.py install` again? I suspect that's the issue.

**Comment by sbarratt** [comment] 2020-05-31 02:25
It's now all magically working, without upgrading setuptools.

**Comment by bstellato** [comment] 2020-06-30 14:51
It was related to including the `qdldl` sources in `MANIFEST.in`. It is fixed in the latest release and the `conda-forge` package is now available.

**Closed by bstellato** 2020-06-30 14:51 UTC
